version: '3.7'

services:

  db:
    image: 'postgres:11'
    container_name: posgresqldb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-sample03-db-volume:/var/lib/posgresql/data

    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=SuperSecret
      - POSTGRES_DB=demo

    
  pgadmin:
    image: dpage/pgadmin4:6.8
    container_name: pgadmin
    ports:
      - 9090:80
    
    volumes:
      - postgres-sample03-pgadmin-volume:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@mail.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret


volumes:
  postgres-sample03-db-volume:
  postgres-sample03-pgadmin-volume:


networks:
  default:
    name: postgres-sample03-network