version: '3.7'

services: 
  mysql:
    image: 'mysql:8.0.22'
    container_name: db
    ports: 
      - "3306:3306"    
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/setup.sql 
      - todo_mysql_compose_volume:/var/lib/mysql
    
    environment:
      MYSQL_ROOT_PASSWORD : supersecret-root
      MYSQL_DATABASE : todoapp_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD : supersecret
  
  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    links:
      - mysql
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
    
volumes: 
  todo_mysql_compose_volume:
