apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.service.app }}
  ports:
    - protocol : TCP
      port: {{ .Values.serice.port }}
      targetPort: {{ .Values.service.targetport }}
      